name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
          registry-url: https://registry.npmjs.org
      - uses: justgook/setup-elm@1.2.0
        with:
          cache: false
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: install
        run: npm ci && (cd demo && npm ci)
      - name: build
        run: npm run build && (cd demo && npm run build)
      - name: test
        run: npm test
      - name: npm publish
        if: ${{ github.event_name == 'push' }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish --access public || true
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: build docs
        run: |
      - name: deploy docs
        run: |
          cd demo/dist
          git init
          git checkout -b gh-pages
          git add -A
          git commit -m "Deploy"
          git push -f git@github.com:andreasewering/travelm-agency.git gh-pages
