name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
          registry-url: https://registry.npmjs.org
      - uses: justgook/setup-elm@1.2.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: install
        run: npm ci && (cd example && npm ci)
      - name: build
        # need to remove elm-stuff to prevent caching to result in a corrupt elm-stuff error
        run: |
          ls -la
          rm -rf elm-stuff example/elm-stuff example/.parcel-cache
          npm run build
          (cd example && npm run build && npm run build:parcel)
      - name: test
        run: npm test
      - name: npm publish
        if: ${{ github.event_name == 'push' }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish --access public || true
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
